services:


  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - team_sync_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - team_sync_network

  
  userservice:
    build: ./backend/services/userService
    container_name: team-sync-user-service
    image: jitheshmjithooz/team-sync-user-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3007:3007
    networks: 
      - team_sync_network

  notificationservice:
    build: ./backend/services/notificationService
    container_name: team-sync-notification-service
    image: jitheshmjithooz/team-sync-notification-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3001:3001
    networks: 
      - team_sync_network
    
  authenticationservice:
    build: ./backend/services/authenticationService
    container_name: team-sync-authentication-service
    image: jitheshmjithooz/team-sync-authentication-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3002:3002
    networks: 
      - team_sync_network
    
  subscriptionservice:
    build: ./backend/services/subscriptionService
    container_name: team-sync-subscription-service
    image: jitheshmjithooz/team-sync-subscription-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3003:3003
    networks: 
      - team_sync_network
    
  tenantservice:
    build: ./backend/services/tenantService
    container_name: team-sync-tenant-service
    image: jitheshmjithooz/team-sync-tenant-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3004:3004
    networks: 
      - team_sync_network
    
  projectservice:
    build:  ./backend/services/projectService
    container_name: team-sync-project-service
    image: jitheshmjithooz/team-sync-project-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3005:3005
    networks: 
      - team_sync_network
    
  communicationservice:
    build:  ./backend/services/communicationService
    container_name: team-sync-communication-service
    image: jitheshmjithooz/team-sync-communication-service
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 3006:3006
    networks: 
      - team_sync_network

  # frontend:
  #   build: ./frontend
  #   container_name: team-sync-frontend
  #   image: jitheshmjithooz/team-sync-frontend
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     -  ./frontend/.env.local

  #   depends_on:
  #     - subscriptionservice
  #   networks: 
  #     - team_sync_network
    


networks:
  team_sync_network:
    driver: bridge


