apiVersion: v1
kind: ConfigMap
metadata:
  name: authenticationservice-config
  namespace: team-sync
data:
  KAFKA_BROKER: kafka:29092
  SERVICE: authService
  JWT_SECRET_KEY: secret
  JWT_ADMIN_SECRET_KEY: adminSecret
  JWT_OTP_SECRET_KEY: otpSecret
  APIKEY: AIzaSyDvdiau5vmBCW_fMxaJkMrFm4lPfTIra1Q
  AUTHDOMAIN: teamsync-123.firebaseapp.com
  PROJECTID: teamsync-123
  STORAGEBUCKET: teamsync-123.appspot.com


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationservice
  namespace: team-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticationservice
  template:
    metadata:
      labels:
        app: authenticationservice
    spec:
      containers:
        - name: authenticationservice
          image: jitheshmjithooz/team-sync-authentication-service
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: authenticationservice-config
            - secretRef:
                name: app-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: authenticationservice
  namespace: team-sync
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: authenticationservice
