apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: team-sync
data:
  NEXT_PUBLIC_API_URL: http://192.168.49.2/api/
  NEXT_PUBLIC_FIREBASE_APIKEY: AIzaSyDvdiau5vmBCW_fMxaJkMrFm4lPfTIra1Q
  NEXT_PUBLIC_AUTH_DOMAIN: teamsync-123.firebaseapp.com
  NEXT_PUBLIC_PROJECT_ID: teamsync-123
  NEXT_PUBLIC_STORAGE_BUCKET: teamsync-123.appspot.com
  NEXT_PUBLIC_MESSAGING_SENDER_ID: "826575287443"
  NEXT_PUBLIC_APP_ID: 1:826575287443:web:a1491fa8135f7f4c200966
  NEXT_PUBLIC_MEASUREMENT_ID: G-1BTGD39358
  NEXT_PUBLIC_FRONTEND_URL: http://192.168.49.2/
  NEXT_PUBLIC_IMAGE_URL: https://res.cloudinary.com/dsxnkdv2k/image/upload



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: team-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jitheshmjithooz/team-sync-frontend
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: team-sync
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
