apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: team-sync
data:
  KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://:9092"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: team-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: inter-broker
      port: 29092
      targetPort: 29092
  selector:
    app: kafka







