apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: team-sync
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      type: Container
